### ISSUE TITLE
Add 24.75" scale length

### ISSUE THREAD

**Issue by OlMue** [rodrigocfd/string-tension-calc#8]
Hi,
I'm not that big in coding, so please forgive me for opening an issue instead of a PR...
I'm missing the standard Les Paul scale length, i.e. **24.75"**. could you please add this? 24.625" is too short and 25" is too long.

Thanks very much in advance!

P.S.: Great tool!

**Comment by rodrigocfd** [comment]
> so please forgive me for opening an issue instead of a PR...

No problem. I'm actually rewriting this application, so any new PRs for this old codebase would be rejected anyway.

> I'm missing the standard Les Paul scale length, i.e. **24.75"**.

Gibson scale lengths are not that accurate, and changed through the decades, although they always advertised it as 24.75". The consensus, as far as I know, is that the actual scale length is 24.625" – that's why I used it. If I recall correctly, Paul Reed Smith is one of the people who said this.

**Comment by OlMue** [comment]
Oh, I didn't know that! And I never bothered to measure the scale myself. ;-) Just did a quick and dirty measurement on my LP on the D string, which is exactly in the middle of the bridge, and it was 628 mm (don't have an imperial ruler). Which is what Gibson generally advertises in metric. It's about 24.72".

But I guess that it varies with every guitar anyway, so I'm not angry if you don't add it. Thanks for the reply!
